apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: auth-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template: 
    metadata:
      labels: 
        app: auth
    spec:
      containers:
        - name: auth
          image: alexkochev/auth-api-node:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
             