apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: users-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: users
  template: 
    metadata:
      labels: 
        app: users
    spec:
      containers:
        - name: users
          image: alexkochev/users-api-node:latest
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default"
             # value: "10.107.43.131" 
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
