apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: users-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: users
  template: 
    metadata:
      labels: 
        app: users
    spec:
      containers:
        - name: users
          image: alexkochev/users-api-node:v3.9
          env:
            - name: AUTH_ADDRESS
              value: "10.97.174.199" 
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
